services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend